name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: linux
            arch: amd64
            ext: ''
          - os: linux
            arch: arm64
            ext: ''
          - os: darwin
            arch: amd64
            ext: ''
          - os: darwin
            arch: arm64
            ext: ''
          - os: windows
            arch: amd64
            ext: '.exe'
    steps:
      - uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: 'stable'
          check-latest: true

      - name: Build binary
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
          CGO_ENABLED: 0
        run: |
          go build -ldflags="-s -w" -o logchecker-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.ext }} cmd/logchecker/main.go

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: logchecker-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.ext }}
